source 'https://rubygems.org'

gem 'rake'
gem 'tomlrb'
gem 'foodcritic', '~> 6.0'
gem 'rubocop', '~> 0.37'
gem 'berkshelf', '~> 4.1'
gem 'chefspec', '~> 4.5'
gem 'test-kitchen', '~> 1.5'
gem 'kitchen-vagrant', '~> 0.19'
gem 'kitchen-docker'
gem 'winrm-fs'
gem 'stove'
